src/gz redmi_ax3000_core https://qwqgong-ui.github.io/Redmi_AX3000_immortalwrt/targets/qualcommax/ipq50xx/packages
src/gz redmi_ax3000_base https://qwqgong-ui.github.io/Redmi_AX3000_immortalwrt/packages/aarch64_cortex-a53/base
src/gz redmi_ax3000_luci https://qwqgong-ui.github.io/Redmi_AX3000_immortalwrt/packages/aarch64_cortex-a53/luci
src/gz redmi_ax3000_packages https://qwqgong-ui.github.io/Redmi_AX3000_immortalwrt/packages/aarch64_cortex-a53/packages
src/gz redmi_ax3000_routing https://qwqgong-ui.github.io/Redmi_AX3000_immortalwrt/packages/aarch64_cortex-a53/routing
src/gz redmi_ax3000_telephony https://qwqgong-ui.github.io/Redmi_AX3000_immortalwrt/packages/aarch64_cortex-a53/telephony
